# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.5', '3.6', '3.7', '3.8', '3.9' ]
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        python-version: 3.8
        activate-environment: testenv
        channels: conda-forge
    - name: Setup Python ${{ matrix.python-version }} with Conda
      run: conda create -q -n env python=${{ matrix.python-version }}
    - name: Install Shut
      run: python -m pip install shut==0.18.2 -q
    - name: Test
      run: PYTHON=$CONDA/envs/env/bin/python shut pkg test --isolate
    - name: Verify package metadata
      run: shut pkg update --verify

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -q shut==0.18.2 -q
    - name: Shut publish
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
      run: |
        shut pkg update --verify-tag "$GITHUB_REF"
        shut pkg publish warehouse:pypi --test
        shut pkg publish warehouse:pypi
